/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tenda.app;

import tenda.list.LinkedList;

import static tenda.utilities.StringUtils.join;
import static tenda.utilities.StringUtils.split;
import static tenda.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
       

        System.out.println("Hola mindo.");
    }
}
